version: "3.8"

services:
  postgresql:
    image: postgres:15.1
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_EXPOSE_PORT}:5432
    profiles:
      - postgres
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 80
    ports:
      - ${PGADMIN_EXPOSE_PORT}:80
    volumes:
      - pgadmin_dev_data:/var/lib/pgadmin
    profiles:
      - postgres

  mail:
    image: sj26/mailcatcher:latest
    ports:
      - "${MAILCATCHER_PORT}:1080"
      - "10250:1025"
    profiles:
      - mail

volumes:
  postgres_dev_data:
  pgadmin_dev_data: